/*
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.imt.dsl.ds.jallais.exo2.Exo2RuntimeModule;
import fr.imt.dsl.ds.jallais.exo2.Exo2StandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Exo2IdeSetup extends Exo2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Exo2RuntimeModule(), new Exo2IdeModule()));
	}
	
}
