/*
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Exo2UiModule extends AbstractExo2UiModule {

	public Exo2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
