/*
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Exo2StandaloneSetup extends Exo2StandaloneSetupGenerated {

	public static void doSetup() {
		new Exo2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
