/**
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.exo2.impl;

import fr.imt.dsl.ds.jallais.exo2.exo2.Button;
import fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package;
import fr.imt.dsl.ds.jallais.exo2.exo2.Frame;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.ButtonImpl#getText <em>Text</em>}</li>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.ButtonImpl#getRedirectTo <em>Redirect To</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ButtonImpl extends GuiComponentImpl implements Button
{
  /**
   * The default value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected static final String TEXT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected String text = TEXT_EDEFAULT;

  /**
   * The cached value of the '{@link #getRedirectTo() <em>Redirect To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRedirectTo()
   * @generated
   * @ordered
   */
  protected Frame redirectTo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ButtonImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Exo2Package.Literals.BUTTON;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getText()
  {
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setText(String newText)
  {
    String oldText = text;
    text = newText;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Exo2Package.BUTTON__TEXT, oldText, text));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Frame getRedirectTo()
  {
    if (redirectTo != null && redirectTo.eIsProxy())
    {
      InternalEObject oldRedirectTo = (InternalEObject)redirectTo;
      redirectTo = (Frame)eResolveProxy(oldRedirectTo);
      if (redirectTo != oldRedirectTo)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, Exo2Package.BUTTON__REDIRECT_TO, oldRedirectTo, redirectTo));
      }
    }
    return redirectTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Frame basicGetRedirectTo()
  {
    return redirectTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRedirectTo(Frame newRedirectTo)
  {
    Frame oldRedirectTo = redirectTo;
    redirectTo = newRedirectTo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Exo2Package.BUTTON__REDIRECT_TO, oldRedirectTo, redirectTo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Exo2Package.BUTTON__TEXT:
        return getText();
      case Exo2Package.BUTTON__REDIRECT_TO:
        if (resolve) return getRedirectTo();
        return basicGetRedirectTo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Exo2Package.BUTTON__TEXT:
        setText((String)newValue);
        return;
      case Exo2Package.BUTTON__REDIRECT_TO:
        setRedirectTo((Frame)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Exo2Package.BUTTON__TEXT:
        setText(TEXT_EDEFAULT);
        return;
      case Exo2Package.BUTTON__REDIRECT_TO:
        setRedirectTo((Frame)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Exo2Package.BUTTON__TEXT:
        return TEXT_EDEFAULT == null ? text != null : !TEXT_EDEFAULT.equals(text);
      case Exo2Package.BUTTON__REDIRECT_TO:
        return redirectTo != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (text: ");
    result.append(text);
    result.append(')');
    return result.toString();
  }

} //ButtonImpl
