/**
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.exo2.impl;

import fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package;
import fr.imt.dsl.ds.jallais.exo2.exo2.GuiComponent;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Gui Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GuiComponentImpl extends MinimalEObjectImpl.Container implements GuiComponent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GuiComponentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Exo2Package.Literals.GUI_COMPONENT;
  }

} //GuiComponentImpl
