/*
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.parser.antlr;

import com.google.inject.Inject;
import fr.imt.dsl.ds.jallais.exo2.parser.antlr.internal.InternalExo2Parser;
import fr.imt.dsl.ds.jallais.exo2.services.Exo2GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Exo2Parser extends AbstractAntlrParser {

	@Inject
	private Exo2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExo2Parser createParser(XtextTokenStream stream) {
		return new InternalExo2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GUI";
	}

	public Exo2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Exo2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
