/**
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.exo2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.Button#getText <em>Text</em>}</li>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.Button#getRedirectTo <em>Redirect To</em>}</li>
 * </ul>
 *
 * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getButton()
 * @model
 * @generated
 */
public interface Button extends GuiComponent
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getButton_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Button#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Redirect To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Redirect To</em>' reference.
   * @see #setRedirectTo(Frame)
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getButton_RedirectTo()
   * @model
   * @generated
   */
  Frame getRedirectTo();

  /**
   * Sets the value of the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Button#getRedirectTo <em>Redirect To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Redirect To</em>' reference.
   * @see #getRedirectTo()
   * @generated
   */
  void setRedirectTo(Frame value);

} // Button
