/**
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.exo2;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Factory
 * @model kind="package"
 * @generated
 */
public interface Exo2Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "exo2";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imt.fr/dsl/ds/jallais/exo2/Exo2";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "exo2";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Exo2Package eINSTANCE = fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl.init();

  /**
   * The meta object id for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.GUIImpl <em>GUI</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.GUIImpl
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getGUI()
   * @generated
   */
  int GUI = 0;

  /**
   * The feature id for the '<em><b>Frames</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__FRAMES = 0;

  /**
   * The number of structural features of the '<em>GUI</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.FrameImpl <em>Frame</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.FrameImpl
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getFrame()
   * @generated
   */
  int FRAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__TITLE = 1;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__WIDTH = 2;

  /**
   * The feature id for the '<em><b>Lenght</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__LENGHT = 3;

  /**
   * The feature id for the '<em><b>Sections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__SECTIONS = 4;

  /**
   * The number of structural features of the '<em>Frame</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.GuiComponentImpl <em>Gui Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.GuiComponentImpl
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getGuiComponent()
   * @generated
   */
  int GUI_COMPONENT = 3;

  /**
   * The number of structural features of the '<em>Gui Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI_COMPONENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.SectionImpl <em>Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.SectionImpl
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getSection()
   * @generated
   */
  int SECTION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__NAME = GUI_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__ELEMENTS = GUI_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION_FEATURE_COUNT = GUI_COMPONENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.LabelImpl
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getLabel()
   * @generated
   */
  int LABEL = 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__TEXT = GUI_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = GUI_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.ButtonImpl
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getButton()
   * @generated
   */
  int BUTTON = 5;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__TEXT = GUI_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Redirect To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__REDIRECT_TO = GUI_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = GUI_COMPONENT_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link fr.imt.dsl.ds.jallais.exo2.exo2.GUI <em>GUI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GUI</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.GUI
   * @generated
   */
  EClass getGUI();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imt.dsl.ds.jallais.exo2.exo2.GUI#getFrames <em>Frames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Frames</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.GUI#getFrames()
   * @see #getGUI()
   * @generated
   */
  EReference getGUI_Frames();

  /**
   * Returns the meta object for class '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame <em>Frame</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Frame</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Frame
   * @generated
   */
  EClass getFrame();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getName()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getTitle()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Title();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getWidth()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Width();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getLenght <em>Lenght</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lenght</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getLenght()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Lenght();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getSections <em>Sections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sections</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getSections()
   * @see #getFrame()
   * @generated
   */
  EReference getFrame_Sections();

  /**
   * Returns the meta object for class '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Section <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Section</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Section
   * @generated
   */
  EClass getSection();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Section#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Section#getName()
   * @see #getSection()
   * @generated
   */
  EAttribute getSection_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Section#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Section#getElements()
   * @see #getSection()
   * @generated
   */
  EReference getSection_Elements();

  /**
   * Returns the meta object for class '{@link fr.imt.dsl.ds.jallais.exo2.exo2.GuiComponent <em>Gui Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gui Component</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.GuiComponent
   * @generated
   */
  EClass getGuiComponent();

  /**
   * Returns the meta object for class '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Label#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Label#getText()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Text();

  /**
   * Returns the meta object for class '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Button#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Button#getText()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Text();

  /**
   * Returns the meta object for the reference '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Button#getRedirectTo <em>Redirect To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Redirect To</em>'.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Button#getRedirectTo()
   * @see #getButton()
   * @generated
   */
  EReference getButton_RedirectTo();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Exo2Factory getExo2Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.GUIImpl <em>GUI</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.GUIImpl
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getGUI()
     * @generated
     */
    EClass GUI = eINSTANCE.getGUI();

    /**
     * The meta object literal for the '<em><b>Frames</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GUI__FRAMES = eINSTANCE.getGUI_Frames();

    /**
     * The meta object literal for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.FrameImpl <em>Frame</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.FrameImpl
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getFrame()
     * @generated
     */
    EClass FRAME = eINSTANCE.getFrame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__NAME = eINSTANCE.getFrame_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__TITLE = eINSTANCE.getFrame_Title();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__WIDTH = eINSTANCE.getFrame_Width();

    /**
     * The meta object literal for the '<em><b>Lenght</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__LENGHT = eINSTANCE.getFrame_Lenght();

    /**
     * The meta object literal for the '<em><b>Sections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FRAME__SECTIONS = eINSTANCE.getFrame_Sections();

    /**
     * The meta object literal for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.SectionImpl <em>Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.SectionImpl
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getSection()
     * @generated
     */
    EClass SECTION = eINSTANCE.getSection();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECTION__NAME = eINSTANCE.getSection_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECTION__ELEMENTS = eINSTANCE.getSection_Elements();

    /**
     * The meta object literal for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.GuiComponentImpl <em>Gui Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.GuiComponentImpl
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getGuiComponent()
     * @generated
     */
    EClass GUI_COMPONENT = eINSTANCE.getGuiComponent();

    /**
     * The meta object literal for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.LabelImpl
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__TEXT = eINSTANCE.getLabel_Text();

    /**
     * The meta object literal for the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.ButtonImpl
     * @see fr.imt.dsl.ds.jallais.exo2.exo2.impl.Exo2PackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__TEXT = eINSTANCE.getButton_Text();

    /**
     * The meta object literal for the '<em><b>Redirect To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON__REDIRECT_TO = eINSTANCE.getButton_RedirectTo();

  }

} //Exo2Package
