/**
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.exo2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frame</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getName <em>Name</em>}</li>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getTitle <em>Title</em>}</li>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getWidth <em>Width</em>}</li>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getLenght <em>Lenght</em>}</li>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getSections <em>Sections</em>}</li>
 * </ul>
 *
 * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getFrame()
 * @model
 * @generated
 */
public interface Frame extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getFrame_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getFrame_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(int)
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getFrame_Width()
   * @model
   * @generated
   */
  int getWidth();

  /**
   * Sets the value of the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #getWidth()
   * @generated
   */
  void setWidth(int value);

  /**
   * Returns the value of the '<em><b>Lenght</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lenght</em>' attribute.
   * @see #setLenght(int)
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getFrame_Lenght()
   * @model
   * @generated
   */
  int getLenght();

  /**
   * Sets the value of the '{@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame#getLenght <em>Lenght</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lenght</em>' attribute.
   * @see #getLenght()
   * @generated
   */
  void setLenght(int value);

  /**
   * Returns the value of the '<em><b>Sections</b></em>' containment reference list.
   * The list contents are of type {@link fr.imt.dsl.ds.jallais.exo2.exo2.Section}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sections</em>' containment reference list.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getFrame_Sections()
   * @model containment="true"
   * @generated
   */
  EList<Section> getSections();

} // Frame
