/**
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.exo2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GUI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.dsl.ds.jallais.exo2.exo2.GUI#getFrames <em>Frames</em>}</li>
 * </ul>
 *
 * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getGUI()
 * @model
 * @generated
 */
public interface GUI extends EObject
{
  /**
   * Returns the value of the '<em><b>Frames</b></em>' containment reference list.
   * The list contents are of type {@link fr.imt.dsl.ds.jallais.exo2.exo2.Frame}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frames</em>' containment reference list.
   * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getGUI_Frames()
   * @model containment="true"
   * @generated
   */
  EList<Frame> getFrames();

} // GUI
