/**
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.exo2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gui Component</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.imt.dsl.ds.jallais.exo2.exo2.Exo2Package#getGuiComponent()
 * @model
 * @generated
 */
public interface GuiComponent extends EObject
{
} // GuiComponent
