/*
 * generated by Xtext 2.28.0
 */
package fr.imt.dsl.ds.jallais.exo2.ui;

import com.google.inject.Injector;
import fr.imt.dsl.ds.jallais.exo2.ui.internal.Exo2Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Exo2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Exo2Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Exo2Activator activator = Exo2Activator.getInstance();
		return activator != null ? activator.getInjector(Exo2Activator.FR_IMT_DSL_DS_JALLAIS_EXO2_EXO2) : null;
	}

}
